version: "3.8"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "25m"
    max-file: "4"

services:
  proxy:
    image: jatinkpa/flutter-web-portfolio:0.1
    ports:
      - '8080:80'
    volumes:
      - ./nginx_internal.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    logging: *default-logging
